### PR TITLE
docs(website): add more detail to Run a Cannon Package page

### PR DESCRIPTION
**Pull request by agaw**
This PR adds a few extra hints in the Getting Started guide - based on my own experience following the instructions on the Run a Cannon Package page. For reference, the updated package looks like this:

run-a-cannon-package-updated

### CODE REVIEW

**Comment by FuzzB0t** [comment]
Thanks for your contribution to our Docs @agaw! Will take a look at this and review it ASAP.

**Comment by FuzzB0t** [comment]
Hey @agaw! I've got some changes to add to this PR before merging, If you could please enable the "Allow edits by maintainers" feature on this PR so I can add them and merge this that would be great. Thanks!

**Comment by FuzzB0t** [comment]
Closing in favor of #535

**Comment by agaw** [comment]
Just saw your comment now, thanks for helping getting this merged @FuzzB0t!

**Pull request closed without merging**
